# Generated by Django 5.1 on 2024-08-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sonho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('emocao', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('nivel_lucidez', models.IntegerField()),
                ('data', models.DateField()),
                ('duracao', models.DurationField()),
            ],
        ),
    ]
